"""Persistence of the §24.2 artifacts on the migrated schema (§24.2, §27, §32).

The table is the one revision ``0005`` created, plus the two columns revision
``0013`` adds because the contract and the client both need them:
``request_id`` (an artifact is delivered *for* a request, and
``GET /v1/artifacts?request_id=`` is how it is found again) and ``created_at``.

``artifact_id_sequences`` (revision ``0013``) is the allocator behind the §24.2
``ART_{YYYY}_{SEQ6}`` identifier: one row per year, incremented inside a
transaction, which is what keeps the sequence unique across API workers and
across restarts. An in-memory counter cannot do that, so it is only the
no-database fallback (see ``app.artifacts.packager.artifact_sequence``).

``artifact_lineage`` (0005) is not written yet: the §24.2 record already carries
``source_ids``/``dataset_ids``/``transformation_ids`` inline, and filling a
second copy has to be decided together with the ``datasets`` materialisation
(conformance plan, lot L3).
"""

from __future__ import annotations

from collections.abc import Mapping
from datetime import UTC, datetime
from typing import Any

from sqlalchemy import (
    BigInteger,
    Boolean,
    Column,
    DateTime,
    Float,
    Integer,
    MetaData,
    String,
    Table,
    Text,
    insert,
    select,
    update,
)

from app.artifacts.packager.artifact_sequence import artifact_year, format_artifact_id
from app.storage.repositories.table_repository import (
    JSON_TYPE,
    TableRepository,
    as_datetime,
    as_iso,
)

__all__ = ["ArtifactRepository", "artifact_id_sequences_table", "artifacts_table"]

artifacts_metadata = MetaData()

artifacts_table = Table(
    "artifacts",
    artifacts_metadata,
    Column("artifact_id", String(64), primary_key=True),
    Column("artifact_type", String(32), nullable=False),
    Column("file_name", String(512), nullable=False),
    Column("mime_type", String(255), nullable=False),
    Column("version", String(32), nullable=False),
    Column("size_bytes", BigInteger, nullable=False),
    Column("sha256", String(64), nullable=False),
    Column("storage_ref", Text, nullable=False),
    Column("purpose", Text, nullable=False),
    Column("source_ids", JSON_TYPE, nullable=False),
    Column("dataset_ids", JSON_TYPE, nullable=False),
    Column("transformation_ids", JSON_TYPE, nullable=False),
    Column("quality_score", Float, nullable=True),
    Column("confidence_score", Float, nullable=True),
    Column("provenance_complete", Boolean, nullable=False),
    Column("status", String(32), nullable=False),
    # Revision 0013 — the request an artifact was delivered for.
    Column("request_id", String(64), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=True),
    # Revision 0016 — §18.2: set when the record is soft-deleted; a read
    # filters on ``deleted_at IS NULL`` (partial index of the same name).
    Column("deleted_at", DateTime(timezone=True), nullable=True),
)

artifact_id_sequences_table = Table(
    "artifact_id_sequences",
    artifacts_metadata,
    # ``autoincrement=False`` to match revision 0013: the year is written by the
    # allocator, never generated by the database.
    Column("year", Integer, primary_key=True, autoincrement=False),
    Column("last_value", BigInteger, nullable=False),
)


def as_list(value: Any) -> list[Any]:
    """Return *value* as a list, tolerating a JSON array stored as a plain string."""
    if isinstance(value, list):
        return value
    if isinstance(value, str):
        import json

        try:
            parsed = json.loads(value)
        except (TypeError, ValueError):
            return []
        return parsed if isinstance(parsed, list) else []
    return []


def to_artifact_response(row: Mapping[str, Any]) -> dict[str, Any]:
    """Map one ``artifacts`` row onto the §24.2 JSON projection."""
    data = dict(row)
    return {
        "artifact_id": data.get("artifact_id"),
        "request_id": data.get("request_id"),
        "artifact_type": data.get("artifact_type"),
        "file_name": data.get("file_name"),
        "mime_type": data.get("mime_type"),
        "version": data.get("version"),
        "size_bytes": data.get("size_bytes"),
        "sha256": data.get("sha256"),
        "storage_ref": data.get("storage_ref"),
        "purpose": data.get("purpose"),
        "source_ids": as_list(data.get("source_ids")),
        "dataset_ids": as_list(data.get("dataset_ids")),
        "transformation_ids": as_list(data.get("transformation_ids")),
        "quality_score": data.get("quality_score"),
        "confidence_score": data.get("confidence_score"),
        "provenance_complete": bool(data.get("provenance_complete")),
        "status": data.get("status") or "available",
        "created_at": as_iso(data.get("created_at")),
        # Décision ``0016`` : un artefact supprimé logiquement reste en base, et la
        # date de suppression fait partie de ce que l'API doit dire — sans elle, un
        # appelant ne peut pas distinguer « supprimé » de « jamais livré ».
        "deleted_at": as_iso(data.get("deleted_at")),
    }


class ArtifactRepository(TableRepository):
    """Persistence of the §24.2 artifacts."""

    _metadata = artifacts_metadata
    _table = artifacts_table

    @classmethod
    async def get(cls, engine: Any, artifact_id: str) -> dict[str, Any] | None:
        """Return one artifact by its identifier, or ``None``."""
        await cls.ensure_table(engine)
        async with engine.connect() as conn:
            result = await conn.execute(
                select(artifacts_table).where(artifacts_table.c.artifact_id == artifact_id)
            )
            row = result.mappings().first()
        return to_artifact_response(row) if row else None

    @classmethod
    async def list_for_request(
        cls,
        engine: Any,
        request_id: str,
        limit: int = 100,
    ) -> list[dict[str, Any]]:
        """Return the artifacts delivered for *request_id*, newest first."""
        await cls.ensure_table(engine)
        async with engine.connect() as conn:
            result = await conn.execute(
                select(artifacts_table)
                .where(artifacts_table.c.request_id == request_id)
                .order_by(
                    artifacts_table.c.created_at.desc(), artifacts_table.c.artifact_id.desc()
                )
                .limit(limit)
            )
            rows = result.mappings().all()
        return [to_artifact_response(row) for row in rows]

    @classmethod
    async def list_all(cls, engine: Any, limit: int = 100) -> list[dict[str, Any]]:
        """Return the artifacts of the instance, newest first."""
        await cls.ensure_table(engine)
        async with engine.connect() as conn:
            result = await conn.execute(
                select(artifacts_table)
                .order_by(
                    artifacts_table.c.created_at.desc(), artifacts_table.c.artifact_id.desc()
                )
                .limit(limit)
            )
            rows = result.mappings().all()
        return [to_artifact_response(row) for row in rows]

    @classmethod
    async def create(cls, engine: Any, record: Mapping[str, Any]) -> dict[str, Any]:
        """Insert one §24.2 artifact and return its stored representation.

        Idempotent on ``artifact_id``: re-delivering the same record (a retried
        request, a replayed background task) returns the row already stored
        instead of raising a primary-key violation (CODING_RULES §1.10).
        """
        await cls.ensure_table(engine)
        artifact_id = str(record.get("artifact_id") or "")
        if not artifact_id:
            raise ValueError("artifact_id is required to persist an artifact (§24.2)")
        existing = await cls.get(engine, artifact_id)
        if existing is not None:
            return existing

        now = datetime.now(UTC)
        row: dict[str, Any] = {
            "artifact_id": artifact_id,
            "artifact_type": str(record.get("artifact_type") or "other"),
            "file_name": str(record.get("file_name") or ""),
            "mime_type": str(record.get("mime_type") or "application/octet-stream"),
            "version": str(record.get("version") or "1.0.0"),
            "size_bytes": int(record.get("size_bytes") or 0),
            "sha256": str(record.get("sha256") or ""),
            "storage_ref": str(record.get("storage_ref") or ""),
            "purpose": str(record.get("purpose") or ""),
            "source_ids": as_list(record.get("source_ids")),
            "dataset_ids": as_list(record.get("dataset_ids")),
            "transformation_ids": as_list(record.get("transformation_ids")),
            "quality_score": record.get("quality_score"),
            "confidence_score": record.get("confidence_score"),
            "provenance_complete": bool(record.get("provenance_complete")),
            "status": str(record.get("status") or "available"),
            "request_id": record.get("request_id"),
            "created_at": as_datetime(record.get("created_at"), now),
        }
        async with engine.begin() as conn:
            await conn.execute(insert(artifacts_table).values(**row))
        return to_artifact_response(row)

    @classmethod
    async def allocate_artifact_id(cls, engine: Any, year: int | None = None) -> str:
        """Return the next §24.2 ``ART_{YYYY}_{SEQ6}`` identifier of *year*.

        The increment happens in the database, inside one transaction, on a
        single row per year: two API workers asking at the same time get two
        different identifiers, and a restart does not restart the sequence.

        Args:
            engine: Async engine bound to the migrated database.
            year: Calendar year of the sequence (UTC by default).

        Returns:
            The allocated identifier.

        Raises:
            ValidationError: When the yearly identifier space is exhausted.
        """
        await cls.ensure_table(engine)
        target = year if year is not None else artifact_year()
        async with engine.begin() as conn:
            if conn.dialect.name == "postgresql":
                from sqlalchemy.dialects.postgresql import insert as pg_insert

                statement = (
                    pg_insert(artifact_id_sequences_table)
                    .values(year=target, last_value=1)
                    .on_conflict_do_update(
                        index_elements=[artifact_id_sequences_table.c.year],
                        set_={"last_value": artifact_id_sequences_table.c.last_value + 1},
                    )
                    .returning(artifact_id_sequences_table.c.last_value)
                )
                value = (await conn.execute(statement)).scalar_one()
            else:
                # SQLite has no ``ON CONFLICT ... RETURNING``: read-then-write
                # inside the same transaction is enough for the single-process
                # use it is reserved for.
                result = await conn.execute(
                    select(artifact_id_sequences_table.c.last_value).where(
                        artifact_id_sequences_table.c.year == target
                    )
                )
                current = result.scalar_one_or_none()
                value = (int(current) if current is not None else 0) + 1
                if current is None:
                    await conn.execute(
                        insert(artifact_id_sequences_table).values(
                            year=target, last_value=value
                        )
                    )
                else:
                    await conn.execute(
                        update(artifact_id_sequences_table)
                        .where(artifact_id_sequences_table.c.year == target)
                        .values(last_value=value)
                    )
        return format_artifact_id(target, int(value))

    @classmethod
    async def soft_delete(cls, engine: Any, artifact_id: str) -> dict[str, Any] | None:
        """Remove one artifact from the active set (§18.2, décision ``0016``).

        Aucune suppression physique : ``status`` passe à ``deleted`` **et**
        ``deleted_at`` est renseigné — les deux marques que la route de
        téléchargement refuse (``410 Gone``). La ligne, ses versions et son
        lineage restent lisibles : une suppression doit rester explicable, et
        l'index partiel ``ix_artifacts_not_deleted`` est ce sur quoi une lecture
        §18.2 filtre.

        Args:
            engine: moteur de base de données.
            artifact_id: l'artefact à retirer de l'ensemble actif.

        Returns:
            L'artefact relu (marqué), ou ``None`` s'il n'existe pas.
        """
        await cls.ensure_table(engine)
        async with engine.begin() as conn:
            result = await conn.execute(
                update(artifacts_table)
                .where(
                    artifacts_table.c.artifact_id == artifact_id,
                    artifacts_table.c.deleted_at.is_(None),
                )
                .values(status="deleted", deleted_at=datetime.now(UTC))
            )
            if not result.rowcount:
                return None
        return await cls.get(engine, artifact_id)
